version: "3"
services:

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    restart: unless-stopped
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "192.168.8.12:50070"
    ports:
      - "50075:50075"

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: aguardio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_sensor_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  mongo.db:
    container_name: mongo.db
    image: mongo:latest
    volumes:
      - mongo.vol:/data/db
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    ports:
      - "27017:27017"
      
volumes:
  postgres_sensor_data:
  mongo.vol:
    name: "mongo.vol"
  datanode:
    name: datanode
